<ul class="control menu">
	<li n:if="$useHomepage" n:class="$homepage->isCurrent ? current">
		<a href="{$homepage->url}" n:attr="title => $homepage->title">{$homepage->label}</a>
	</li>

	{block #menu}
	<li n:foreach="$children as $item" n:class="$iterator->last ? last, $item->isCurrent ? current">
		<a href="{$item->url}" n:attr="title => $item->title">{$item->label}</a>
		
		{if $renderChildren && count($item->getComponents()) > 0}
		<ul>
			{include #menu, children => $item->getComponents()}
		</ul>
		{/if}
	</li>
	{/block}
</ul>
